App:
  image: reviewninja/review.ninja
  ports:
   - "5000:5000"
  links:
   - Mongo
   - Slack
  volumes:
   # - path/to/certificates
  environment:
    MONGODB: mongodb://Mongo/reviewninja
    SMTP_HOST:
    SMTP_FROM:
    SMTP_TLS:
    CERT:
    PROTOCOL: https
    HOST:
    GITHUB_CLIENT:
    GITHUB_SECRET:
    GITHUB_HOST:
    GITHUB_API_HOST:
    GITHUB_API_PATHPREFIX: /api/v3
    GITHUB_USER:
    GITHUB_PASS:
    SLACK_HOST: Slack
    SLACK_PORT: 8080

Nginx:
  image: nginx
  links:
   - App
  ports:
   - "80:80"
   - "443:443"
  environment:
    APP_HOST: App
  volumes:
   # - /path/to/sites-enabled:/etc/nginx/sites-enabled
   # - /path/to/nginx/certs:/etc/nginx/certs

Slack:
  image: reviewninja/slack-hooks
  ports:
   - "8080:80"
  environment:
    # JAVA_OPTS: -Dhttps.proxyHost=yourproxy.example.com -Dhttps.proxyPort=whatever

Mongo:
  image: mongo
  volumes:
   # - /path/to/db:/data/db

Elasticsearch:
  image: elasticsearch
  ports:
   - "9200:9200"
   - "9300:9300"

Logstash:
  image: ggruiz/logstash
  ports:
   - "6000:6000"
   - "6000:6000/udp"
  links:
   - Elasticsearch:elasticsearch
  command: -f /opt/logstash/logstash.conf
  environment:
    LOGSPOUT: ignore

Kibana:
  image: kibana
  ports:
   - "5601:5601"
  links:
   - Elasticsearch: elasticsearch

Logspout:
  image: ggruiz/logspout
  volumes:
   - /var/run/docker.sock:/tmp/docker.sock
  links:
   - Logstash 
  environment:
    ROUTE_URIS: logstash://Logstash:6000
