App:
  image: reviewninja/review.ninja
  ports:
   - "5000:5000"
  links:
   - Mongo
   - Slack
  environment:
    MONGODB: mongodb://Mongo/reviewninja
    SMTP_HOST:
    SMTP_TLS:
    CERT:
    PROTOCOL:
    HOST:
    GITHUB_CLIENT: 
    GITHUB_SECRET:
    GITHUB_HOST:
    GITHUB_API_HOST:
    GITHUB_API_PATHPREFIX:
    GITHUB_USER:
    GITHUB_PASS:
    SLACK_HOST: Slack
    SLACK_PORT: 8080

Nginx:
  image: reviewninja/nginx
  links:
   - App
  ports:
   - "80:80"
   - "443:443"
  environment:
    APP_HOST: App

Slack:
  image: reviewninja/slack-hooks
  ports:
   - "8080:80"

Mongo:
  image: mongo

Elasticsearch:
  image: elasticsearch
  ports:
   - "9200:9200"
  volumes:
   - /var/lib/elasticsearch

Logstash:
  image: ggruiz/logstash
  ports:
   - "6000:6000"
   - "6000:6000/udp"
  links:
   - Elasticsearch
  environment:
    LOGSPOUT: ignore
  command: -f /opt/logstash/logstash.conf

Kibana:
  image: clusterhq/kibana
  ports:
   - "6600:8080"

Logspout:
  image: gliderlabs/logspout
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
  command: syslog://localhost:6000